### ISSUE TITLE
第28行出错了

### ISSUE THREAD

**Issue by ayiui4566** [longbill/EndSkin#1]
this.templateReader = function(f,cb)
	{
		// var file = RootPath+f;
		var file = f;
		return fs.readFileSync(file,'utf-8');
	}
这里出错了，
Error: ENOENT: no such file or directory, open 'G:\1.web前端\node\express\view\G:\1.web前端\node\express\view\test1.html'
去掉拼接RootPath就好了

**Comment by longbill** [comment]
你仔细看看readme.md。  用法是先指定一个root， 然后EndSkin.create('index.html')。 这里传入的是相对于root的路径。 你先指定了一个root，然后create的时候又写绝对路径肯定不对啊。

**Comment by ayiui4566** [comment]
我没有create啊，大哥。

**Comment by ayiui4566** [comment]
Express 3.x,4.x Support 我是用的这个。

**Comment by ayiui4566** [comment]
Error: ENOENT: no such file or directory, open 'G:\1.web前端\node\express\view\G:\1.web前端\node\express\view\test1.html'

**Comment by ayiui4566** [comment]
/*
* express 3.x support
*/
exports.renderFile = function(path, options, fn)
{
	console.log(path);//G:\1.web前端\node\express\view\test1.html

**Comment by ayiui4566** [comment]
不支持express 4.x？看看这个path直接是绝对路径，
